// <auto-generated />
using System;
using DiveLog.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiveLog.DAL.Migrations
{
    [DbContext(typeof(DiveLogContext))]
    [Migration("20190610202346_AddedDataPoints")]
    partial class AddedDataPoints
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiveLog.DAL.Models.DataPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Depth");

                    b.Property<long?>("LogEntryId");

                    b.Property<int>("Time");

                    b.HasKey("Id");

                    b.HasIndex("LogEntryId");

                    b.ToTable("DataPoint");
                });

            modelBuilder.Entity("DiveLog.DAL.Models.LogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DiveDate");

                    b.Property<int>("DiveType");

                    b.Property<short>("SampleRate");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("DiveLog.DAL.Models.DataPoint", b =>
                {
                    b.HasOne("DiveLog.DAL.Models.LogEntry")
                        .WithMany("DataPoints")
                        .HasForeignKey("LogEntryId");
                });
#pragma warning restore 612, 618
        }
    }
}
